"""agrega day y completed a exercises

Revision ID: 57f2c61698ad
Revises: 96dc108b9359
Create Date: 2026-07-04 22:16:37.774358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f2c61698ad'
down_revision = '96dc108b9359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('completed')
        batch_op.drop_column('day')

    # ### end Alembic commands ###
